services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      
    volumes:
      - ./:/var/www/app
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://symfony:password@mysql:3306/symfony?serverVersion=8.0
    networks:
      - internal-network

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - internal-network

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge

volumes:
  mysql_data: 